### Login
# @name login
POST http://localhost:8085/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}


### Get Weather by City
GET http://localhost:8085/cities
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

GET http://localhost:8085/cities/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

### Create City
POST http://localhost:8085/cities
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "name": "New City",
    "latitude": 12.345678,
  "longitude": 98.7654321
}

### Update City
PUT http://localhost:8085/cities/2
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "name": "Updated City",
  "latitude": 12.345678,
  "longitude": 98.7654321
}

### Delete City
DELETE http://localhost:8085/cities/2
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

### End of City CRUD Tests