CREATE TABLE IF NOT EXISTS weathers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    city_id INT NOT NULL UNIQUE,
    FOREIGN KEY (city_id) REFERENCES cities(id),
    temperature_c FLOAT NOT NULL,
    `condition` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
